### ISSUE TITLE
sksl files

### ISSUE THREAD

**Issue by limelect** [jimmckeeth/SkiaSimpleShaderViewer#1]
D10.2.3
I have downloaded source files from https://www.shadertoy.com/
and some do not work, language problems I guess?
Is there a fix? or only very simple?

**Comment by viniciusfbb** [comment]
There are several shader languages ​​on the internet. Shadertoy specifically uses the GLSL language on its website. Skia supports SKSL, which was made based on GLSL. That's why GLSL (language that shadertoy uses) and SKSL (language that Skia uses) are almost identical. But there are some differences. Unfortunately these differences are not very well documented, but I will list the main ones here:

1) Uniforms of type samplerXX or sampler2D, like `uniform samplerXX iChannel0;` are declared as shader type, like `uniform shader iChannel0;`

2) The method
```cpp
void mainImage( out vec4 fragColor, in vec2 fragCoord ) {
    ...
}
```
must be declared as:
```cpp
vec4 main( in vec2 fragCoord ) {
    vec4 fragColor;
    ...
    return fragColor;
}
```

3) The defines do not exist in the sksl, so they must be declared as constants:
`#define PI 3.1415`
must be declared as:
`const float PI = 3.1415;`

4) The "texture(" function is the function that reads a certain pixel of an image, through percentage coordinates, that is, from 0..1. The function that reads a pixel of an image in SKSL is the "eval( ", but it doesn't use percentage coordinates, it uses real pixel coordinates. So the code:
`texture(iChannel0, XX);`
It must be replaced by:
`iChannel0.eval(XX * iChannelResolution0.xy)`
where the iChannelResolution0 is the `uniform vec2 iChannelResolution0;`, which you must enter the size of the iChannel0 image before rendering the shader.

It sounds difficult, but it's easier than it looks. After you convert about 3 shaders, you will see this.

There are other differences, a little more rare, that you can solve based on the error messages that you receive from the shader (it reports the line of code with the problem).
There are also some shadertoy codes that are more complex, involving more than 1 shader (BufferA tab, BufferB tab, ...). So first convert only shaders that only have the Image tab.

Any questions we are also available on telegram: https://t.me/skia4delphi
